# Generated by Django 2.2.6 on 2019-10-23 10:23

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import read_statistics.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LabPostType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_name', models.CharField(max_length=17)),
            ],
        ),
        migrations.CreateModel(
            name='LabPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='在此输入贴子标题', max_length=30)),
                ('content', ckeditor.fields.RichTextField()),
                ('created_data', models.DateTimeField(auto_now_add=True)),
                ('edited_data', models.DateTimeField(auto_now=True)),
                ('is_delete', models.BooleanField(default=False)),
                ('author', models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('post_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='post.LabPostType')),
            ],
            options={
                'ordering': ['-created_data'],
            },
            bases=(models.Model, read_statistics.models.ReadNumExpandMethod),
        ),
    ]
