# Generated by Django 2.2.1 on 2019-05-22 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='在此输入贴子标题', max_length=30)),
                ('content', models.TextField(default='在此输入贴子内容')),
                ('created_data', models.DateTimeField(auto_now_add=True)),
                ('edited_data', models.DateTimeField(auto_now=True)),
                ('is_delete', models.BooleanField(default=False)),
            ],
        ),
    ]
