# Generated by Django 2.2.1 on 2019-05-27 03:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0004_auto_20190522_1706'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-created_data']},
        ),
    ]
