# Generated by Django 2.2.6 on 2019-10-02 11:06

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0007_labpost_readed_num'),
    ]

    operations = [
        migrations.AlterField(
            model_name='labpost',
            name='content',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
