# Generated by Django 2.2.6 on 2019-10-02 11:35

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0008_auto_20191002_1906'),
    ]

    operations = [
        migrations.AlterField(
            model_name='labpost',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
    ]
