# Generated by Django 2.2.6 on 2019-10-09 12:52

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0009_auto_20191002_1935'),
    ]

    operations = [
        migrations.AlterField(
            model_name='labpost',
            name='content',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
