# Generated by Django 2.2.1 on 2019-10-02 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('read_statistics', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='readnum',
            name='tag',
        ),
        migrations.AddField(
            model_name='readnum',
            name='read_num',
            field=models.IntegerField(default=0),
        ),
    ]
