# Generated by Django 2.2.6 on 2019-10-23 13:38

from django.db import migrations, models
import file_upload.models


class Migration(migrations.Migration):

    dependencies = [
        ('file_upload', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='file_path',
            field=models.CharField(default=file_upload.models.user_directory_path, max_length=500),
        ),
    ]
